{ lib }:

let
  colorsTomlPath = "/etc/stylix/colors.toml";
in
  if builtins.pathExists colorsTomlPath
  then lib.importTOML colorsTomlPath
  else throw "lib/colors.nix: /etc/stylix/colors.toml not found. Ensure it is generated by your system Stylix module."

