version = 3
final_space = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "os"
  style = "diamond"
  foreground = "p:base00"
  background = "p:base0C"
  leading_diamond = "╭─"
  template = " {{ .Icon }} "

    [blocks.segments.properties]
    alpine = "\uf300"
    arch = "\uf303"
    debian = "\uf306"
    ubuntu = "\uf31c"
    nix = "\uf313"
    macos = "\ue711"
    windows = "\ue70f"
  
  [[blocks.segments]]
  type = "text"
  style = "powerline"
  foreground = "p:base01"
  background = "p:base01"
  powerline_symbol = "\ue0b0"
  template = " "

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  foreground = "p:base00"
  background = "p:base0D"
  powerline_symbol = "\ue0b0"
  template = "  {{ .Path }} "

    [blocks.segments.properties]
    style = "agnoster_short"
    max_depth = 3

  [[blocks.segments]]
  type = "git"
  style = "diamond"
  foreground = "p:base0B"
  background = "p:base00"
  trailing_diamond = "\ue0b0"
  template = " {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <transparent>\ue0b1</> <p:base08>\uf044 {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }} <transparent>\ue0b1</> <p:base0F>\uf046 {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }} <transparent>\ue0b1</> <p:base03>\ueb4b {{ .StashCount }}</>{{ end }} "

    [blocks.segments.properties]
    branch_icon = " "
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "executiontime"
  style = "powerline"
  foreground = "p:base09"
  background = "p:base00"
  invert_powerline = true
  powerline_symbol = "\ue0b2"
  template = " \ueba2 {{ .FormattedMs }} "

    [blocks.segments.properties]
    style = "austin"
    always_enabled = true

  [[blocks.segments]]
  type = "time"
  style = "diamond"
  foreground = "p:base00"
  background = "p:base09"
  invert_powerline = true
  trailing_diamond = "\ue0b4"
  template = " \uf017 {{ .CurrentDate | date .Format }} "

    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:base0C"
  template = "╰─⫸ {{ if .Root }}#{{else}}{{end}}"

