version = 3
final_space = true

[palette]
white = "{{base05}}"
red = "{{base08}}"
orange = "{{base0F}}"
yellow = "{{base09}}"
green = "{{base0B}}"
cyan = "{{base0C}}"
blue = "{{base0D}}"
magenta = "{{base0E}}"
grey = "{{base03}}"
obsidian = "{{base00}}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "os"
  style = "diamond"
  foreground = "p:obsidian"
  background = "p:cyan"
  leading_diamond = "╭─"
  template = " {{ .Icon }} "

    [blocks.segments.properties]
    alpine = "\uf300"
    arch = "\uf303"
    debian = "\uf306"
    ubuntu = "\uf31c"
    nix = "\uf313"
    macos = "\ue711"
    windows = "\ue70f"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  foreground = "p:obsidian"
  background = "p:blue"
  powerline_symbol = "\ue0b0"
  template = " {{ .Path }} "

    [blocks.segments.properties]
    style = "agnoster_short"
    max_depth = 3

  [[blocks.segments]]
  type = "git"
  style = "diamond"
  foreground = "p:green"
  background = "p:obsidian"
  trailing_diamond = "\ue0b0"
  template = " {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <transparent>\ue0b1</> <p:red>\uf044 {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }} <transparent>\ue0b1</> <p:orange>\uf046 {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }} <transparent>\ue0b1</> <p:grey>\ueb4b {{ .StashCount }}</>{{ end }} "

    [blocks.segments.properties]
    branch_icon = " "
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "executiontime"
  style = "powerline"
  foreground = "p:yellow"
  background = "p:obsidian"
  invert_powerline = true
  powerline_symbol = "\ue0b2"
  template = " \ueba2 {{ .FormattedMs }} "

    [blocks.segments.properties]
    style = "austin"
    always_enabled = true

  [[blocks.segments]]
  type = "time"
  style = "diamond"
  foreground = "p:obsidian"
  background = "p:yellow"
  invert_powerline = true
  trailing_diamond = "\ue0b4"
  template = " \uf017 {{ .CurrentDate | date .Format }} "

    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:cyan"
  template = "{{ if .Root }}╰─⫸ #{{ else }}╰─⫸ {{ end }}"

